services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./jumping-jack-db:/data/restore
      - ./scripts/init-restore.sh:/docker-entrypoint-initdb.d/init-restore.sh

  machine-learning-client:
    build: ./machine-learning-client
    container_name: ml-client
    env_file:
      - .env
    volumes:
      - ./machine-learning-client:/app
    depends_on:
      - mongodb

  web-app:
    build: ./web-app
    container_name: web-app
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./web-app:/app
    depends_on:
      - mongodb

volumes:
  mongodb_data:
