services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./jumping-jack-db:/data/restore
      - ./scripts/init-restore.sh:/docker-entrypoint-initdb.d/init-restore.sh
    networks:
      - app-network

  machine-learning-client:
    build: 
      context: ./machine-learning-client
      dockerfile: Dockerfile
    container_name: ml-client
    ports:
      - "8765:8765"  # Expose WebSocket port
    env_file:
      - .env
    volumes:
      - ./machine-learning-client/main.py:/app/main.py
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: always
    hostname: ml-service

  web-app:
    build: ./web-app
    container_name: web-app
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    volumes:
      - ./web-app:/app
    depends_on:
      - mongodb
      - machine-learning-client
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
