name: ml client build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: machine-learning-client

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv sync --dev
          
      - name: Build Docker image
        run: docker build -t ml-client .
      
      - name: Run unit tests in Docker container
        run: docker run --rm ml-client pipenv run pytest
