name: Web App Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-app

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv sync --dev
          pipenv install pytest pytest-cov

      - name: Build Docker image
        run: docker build -t web-app .

      - name: Run unit tests in Docker container
        env:
          MONGO_URI: mongodb://host.docker.internal:27017/test_db
        run: |
          docker run --rm \
            -e MONGO_URI=$MONGO_URI \
            -e PYTHONPATH=/app \
            -e PYTHONUNBUFFERED=1 \
            --network=host \
            --add-host=host.docker.internal:host-gateway \
            web-app pytest -v tests/
