name: Web App Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-app

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv sync --dev
          pipenv install pytest

      - name: Build Docker image
        run: docker build -t web-app .

      - name: Run unit tests
        env:
          MONGO_URI: mongodb://localhost:27017/test_db
        run: |
          pytest tests/ --cov=app --cov-report=xml
